.TH HighLow 6 "11 September 2016" "version 0.31"

.SH NAME
HighLow: A game.

.SH SYNOPSIS
highlow [ -l
.I limit
] [ -u
.I limit
]

.SH DESCRIPTION
It is a simple game where you're supposed to guess the random number the application is generating. You'll get seven tries to do so.
.PP
In the end the game is going to tell you how much levels you managed to cross before losing.

.SH OPTIONS
.TP
.RI "-l " "limit"
.TP
.RI "--llimit " "limit"
Tell the (integer) lower limit to the game.

.TP
.RI "-u " "limit"
.TP
.RI "--ulimit " "limit"
Tell the (integer) upper limit to the game.

.TP
.RI "-g " "number"
.TP
.RI "--guesses " "number"
Tell the (integer) total number of guesses to the game.

.SH BUGS
TBA

.SH AUTHOR
Veer Arjun Singh veerarjunsingh@outlook.com
